version: '3.6'

services:
  #Backend API
  scratchpay:
    container_name: scratchpay
  #image: node:10.15.1
    build: ./
    command: npm start
    working_dir: /usr/src/scratchpay
    ports:
    - "8000:8000"
    volumes:
      - ./:/usr/src/scratchpay